# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form7yKAVrs.ui'
##
## Created by: Qt User Interface Compiler version 6.7.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QTabWidget, QToolButton,
    QWidget)

class Ui_researcher(object):
    def setupUi(self, researcher):
        if not researcher.objectName():
            researcher.setObjectName(u"researcher")
        researcher.setWindowModality(Qt.WindowModality.NonModal)
        researcher.setEnabled(True)
        researcher.resize(600, 70)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(researcher.sizePolicy().hasHeightForWidth())
        researcher.setSizePolicy(sizePolicy)
        researcher.setMinimumSize(QSize(600, 70))
        researcher.setMaximumSize(QSize(1920, 70))
        researcher.setStyleSheet(u"background-color: rgb(31, 31, 31);")
        researcher.setAnimated(True)
        researcher.setDocumentMode(False)
        researcher.setTabShape(QTabWidget.TabShape.Rounded)
        researcher.setDockOptions(QMainWindow.DockOption.AllowTabbedDocks|QMainWindow.DockOption.AnimatedDocks)
        self.actionOpen = QAction(researcher)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(researcher)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.actionExit = QAction(researcher)
        self.actionExit.setObjectName(u"actionExit")
        self.action_search_withoutgpt = QAction(researcher)
        self.action_search_withoutgpt.setObjectName(u"action_search_withoutgpt")
        self.actionhistory = QAction(researcher)
        self.actionhistory.setObjectName(u"actionhistory")
        self.actionhistory.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.actionLast_Saved = QAction(researcher)
        self.actionLast_Saved.setObjectName(u"actionLast_Saved")
        self.actionLast_Saved.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.actionTake = QAction(researcher)
        self.actionTake.setObjectName(u"actionTake")
        self.actionTake.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.actionOpen_Folder = QAction(researcher)
        self.actionOpen_Folder.setObjectName(u"actionOpen_Folder")
        self.actionOpen_Folder.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.actionReset_Url = QAction(researcher)
        self.actionReset_Url.setObjectName(u"actionReset_Url")
        self.actionReset_Url.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.actionInfo = QAction(researcher)
        self.actionInfo.setObjectName(u"actionInfo")
        self.actionNew_Browser = QAction(researcher)
        self.actionNew_Browser.setObjectName(u"actionNew_Browser")
        self.actionNew_Browser.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.actionHide_minimise = QAction(researcher)
        self.actionHide_minimise.setObjectName(u"actionHide_minimise")
        self.actionHide_minimise.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.action_Hide = QAction(researcher)
        self.action_Hide.setObjectName(u"action_Hide")
        self.action_Hide.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.actionBookmarks = QAction(researcher)
        self.actionBookmarks.setObjectName(u"actionBookmarks")
        self.actionBookmarks.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.actionGenerate_PDF = QAction(researcher)
        self.actionGenerate_PDF.setObjectName(u"actionGenerate_PDF")
        self.actionArrange_Windows = QAction(researcher)
        self.actionArrange_Windows.setObjectName(u"actionArrange_Windows")
        self.actionArrange_Windows.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.actionArrange_Windows.setVisible(True)
        self.actionopen_preference = QAction(researcher)
        self.actionopen_preference.setObjectName(u"actionopen_preference")
        self.actionTake_screenshot_each = QAction(researcher)
        self.actionTake_screenshot_each.setObjectName(u"actionTake_screenshot_each")
        self.actionNotes_Maker_with_Gemini = QAction(researcher)
        self.actionNotes_Maker_with_Gemini.setObjectName(u"actionNotes_Maker_with_Gemini")
        self.actionPython_Instant_Code_Tester = QAction(researcher)
        self.actionPython_Instant_Code_Tester.setObjectName(u"actionPython_Instant_Code_Tester")
        self.actionDrag_Notes_maker = QAction(researcher)
        self.actionDrag_Notes_maker.setObjectName(u"actionDrag_Notes_maker")
        self.actionDrag_Notes_maker.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.actionDockview = QAction(researcher)
        self.actionDockview.setObjectName(u"actionDockview")
        self.actionGoogle_Explore = QAction(researcher)
        self.actionGoogle_Explore.setObjectName(u"actionGoogle_Explore")
        self.actionGoogle_Explore.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.actionPython_Code_Tester = QAction(researcher)
        self.actionPython_Code_Tester.setObjectName(u"actionPython_Code_Tester")
        self.actionPython_Code_Tester.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.actionHide_Borders = QAction(researcher)
        self.actionHide_Borders.setObjectName(u"actionHide_Borders")
        self.actionHide_Borders.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.action_clearcache = QAction(researcher)
        self.action_clearcache.setObjectName(u"action_clearcache")
        self.actionRead_chatgpt = QAction(researcher)
        self.actionRead_chatgpt.setObjectName(u"actionRead_chatgpt")
        self.actionClear_History = QAction(researcher)
        self.actionClear_History.setObjectName(u"actionClear_History")
        self.actionShare = QAction(researcher)
        self.actionShare.setObjectName(u"actionShare")
        self.actionShare.setShortcutContext(Qt.ShortcutContext.ApplicationShortcut)
        self.centralwidget = QWidget(researcher)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(600, 0))
        self.centralwidget.setStyleSheet(u"background-color: rgba(0, 0, 0,0);")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(0, -1, 606, 38))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy1)
        self.lineEdit.setMinimumSize(QSize(0, 0))
        self.lineEdit.setMaximumSize(QSize(1920, 70))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit.setStyleSheet(u"background-color: rgb(17, 17, 17);\n"
"alternate-background-color: rgb(225, 225, 225);\n"
"selection-background-color: rgb(137, 143, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"color: rgb(83, 248, 195);")
        self.lineEdit.setMaxLength(1000)
        self.lineEdit.setFrame(False)
        self.lineEdit.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setDragEnabled(True)
        self.lineEdit.setCursorMoveStyle(Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEdit.setClearButtonEnabled(False)
        self.toolButton = QToolButton(self.centralwidget)
        self.toolButton.setObjectName(u"toolButton")
        self.toolButton.setGeometry(QRect(550, 6, 25, 25))
        self.toolButton.setStyleSheet(u"background-color: rgba(255, 255, 255,0);\n"
"color: rgb(0, 255, 126);")
        icon = QIcon()
        icon.addFile(u"../images/search.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QSize(20, 20))
        self.toolButton.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.toolButton.setArrowType(Qt.ArrowType.NoArrow)
        self.toolButton_mic = QToolButton(self.centralwidget)
        self.toolButton_mic.setObjectName(u"toolButton_mic")
        self.toolButton_mic.setGeometry(QRect(524, 6, 25, 25))
        self.toolButton_mic.setStyleSheet(u"background-color: rgba(255, 255, 255,0);")
        icon1 = QIcon()
        icon1.addFile(u"../images/mic.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_mic.setIcon(icon1)
        self.toolButton_mic.setIconSize(QSize(25, 30))
        self.toolButton_2 = QToolButton(self.centralwidget)
        self.toolButton_2.setObjectName(u"toolButton_2")
        self.toolButton_2.setGeometry(QRect(575, 6, 23, 21))
        font1 = QFont()
        font1.setPointSize(36)
        self.toolButton_2.setFont(font1)
        self.toolButton_2.setStyleSheet(u"background-color: rgba(255, 255, 255,0);\n"
"color: rgb(147, 100, 210);")
        researcher.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(researcher)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 600, 33))
        font2 = QFont()
        font2.setPointSize(9)
        font2.setBold(True)
        self.menubar.setFont(font2)
        self.menubar.setStyleSheet(u"color: rgb(155, 155, 255);\n"
"selection-color: rgb(128, 255, 198);\n"
"alternate-background-color: rgb(186, 186, 186);\n"
"background-color: rgb(31, 31, 31);\n"
"selection-background-color: rgb(33, 33, 33);")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        font3 = QFont()
        font3.setPointSize(11)
        self.menuFile.setFont(font3)
        self.menuFile.setAutoFillBackground(False)
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuEdit.setFont(font3)
        self.menuEdit.setTearOffEnabled(False)
        self.menuOptions = QMenu(self.menubar)
        self.menuOptions.setObjectName(u"menuOptions")
        self.menuOptions.setFont(font3)
        self.menuRestore = QMenu(self.menubar)
        self.menuRestore.setObjectName(u"menuRestore")
        self.menuRestore.setFont(font3)
        self.menuDefaults = QMenu(self.menubar)
        self.menuDefaults.setObjectName(u"menuDefaults")
        self.menuDefaults.setFont(font3)
        self.menuScreenshot = QMenu(self.menubar)
        self.menuScreenshot.setObjectName(u"menuScreenshot")
        self.menuScreenshot.setFont(font3)
        self.menuLinks = QMenu(self.menubar)
        self.menuLinks.setObjectName(u"menuLinks")
        self.menuLinks.setFont(font3)
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menuAbout.setFont(font3)
        researcher.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRestore.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuScreenshot.menuAction())
        self.menubar.addAction(self.menuDefaults.menuAction())
        self.menubar.addAction(self.menuLinks.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menuFile.addAction(self.actionNew_Browser)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionGoogle_Explore)
        self.menuEdit.addAction(self.action_search_withoutgpt)
        self.menuOptions.addAction(self.actionHide_minimise)
        self.menuOptions.addAction(self.action_Hide)
        self.menuOptions.addAction(self.actionHide_Borders)
        self.menuOptions.addAction(self.actionArrange_Windows)
        self.menuRestore.addAction(self.actionLast_Saved)
        self.menuRestore.addAction(self.actionReset_Url)
        self.menuRestore.addAction(self.actionClear_History)
        self.menuDefaults.addAction(self.actionPython_Code_Tester)
        self.menuDefaults.addAction(self.actionShare)
        self.menuScreenshot.addAction(self.actionDrag_Notes_maker)
        self.menuScreenshot.addAction(self.actionTake)
        self.menuScreenshot.addAction(self.actionOpen_Folder)
        self.menuScreenshot.addAction(self.actionGenerate_PDF)
        self.menuLinks.addAction(self.actionhistory)
        self.menuLinks.addAction(self.actionBookmarks)
        self.menuAbout.addAction(self.actionInfo)

        self.retranslateUi(researcher)

        QMetaObject.connectSlotsByName(researcher)
    # setupUi

    def retranslateUi(self, researcher):
        researcher.setWindowTitle(QCoreApplication.translate("researcher", u"Commander", None))
        self.actionOpen.setText(QCoreApplication.translate("researcher", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("researcher", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("researcher", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionExit.setText(QCoreApplication.translate("researcher", u"Save and Exit", None))
#if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("researcher", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.action_search_withoutgpt.setText(QCoreApplication.translate("researcher", u"Without GPT", None))
        self.actionhistory.setText(QCoreApplication.translate("researcher", u"Open History", None))
#if QT_CONFIG(whatsthis)
        self.actionhistory.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(shortcut)
        self.actionhistory.setShortcut(QCoreApplication.translate("researcher", u"Shift+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionLast_Saved.setText(QCoreApplication.translate("researcher", u"Last Saved", None))
#if QT_CONFIG(shortcut)
        self.actionLast_Saved.setShortcut(QCoreApplication.translate("researcher", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionTake.setText(QCoreApplication.translate("researcher", u"Take Screenshot", None))
#if QT_CONFIG(shortcut)
        self.actionTake.setShortcut(QCoreApplication.translate("researcher", u"Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen_Folder.setText(QCoreApplication.translate("researcher", u"Open Folder", None))
#if QT_CONFIG(shortcut)
        self.actionOpen_Folder.setShortcut(QCoreApplication.translate("researcher", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionReset_Url.setText(QCoreApplication.translate("researcher", u"Reset Url", None))
#if QT_CONFIG(shortcut)
        self.actionReset_Url.setShortcut(QCoreApplication.translate("researcher", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionInfo.setText(QCoreApplication.translate("researcher", u"Info", None))
        self.actionNew_Browser.setText(QCoreApplication.translate("researcher", u"New Browser", None))
#if QT_CONFIG(shortcut)
        self.actionNew_Browser.setShortcut(QCoreApplication.translate("researcher", u"Ctrl+Shift+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionHide_minimise.setText(QCoreApplication.translate("researcher", u"Minimize", None))
#if QT_CONFIG(shortcut)
        self.actionHide_minimise.setShortcut(QCoreApplication.translate("researcher", u"Ctrl+M", None))
#endif // QT_CONFIG(shortcut)
        self.action_Hide.setText(QCoreApplication.translate("researcher", u"Hide Commander", None))
#if QT_CONFIG(shortcut)
        self.action_Hide.setShortcut(QCoreApplication.translate("researcher", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionBookmarks.setText(QCoreApplication.translate("researcher", u"Bookmarks", None))
#if QT_CONFIG(shortcut)
        self.actionBookmarks.setShortcut(QCoreApplication.translate("researcher", u"Shift+B", None))
#endif // QT_CONFIG(shortcut)
        self.actionGenerate_PDF.setText(QCoreApplication.translate("researcher", u"Screenshots To PDF", None))
        self.actionArrange_Windows.setText(QCoreApplication.translate("researcher", u"Organise Windows", None))
#if QT_CONFIG(shortcut)
        self.actionArrange_Windows.setShortcut(QCoreApplication.translate("researcher", u"Shift+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionopen_preference.setText(QCoreApplication.translate("researcher", u"Open Preference", None))
        self.actionTake_screenshot_each.setText(QCoreApplication.translate("researcher", u"Take Screenshoots (Each)", None))
        self.actionNotes_Maker_with_Gemini.setText(QCoreApplication.translate("researcher", u"Notes Maker with Gemini", None))
        self.actionPython_Instant_Code_Tester.setText(QCoreApplication.translate("researcher", u"Python Instant Code Tester", None))
        self.actionDrag_Notes_maker.setText(QCoreApplication.translate("researcher", u"Notes Maker", None))
#if QT_CONFIG(shortcut)
        self.actionDrag_Notes_maker.setShortcut(QCoreApplication.translate("researcher", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionDockview.setText(QCoreApplication.translate("researcher", u"Dockview", None))
        self.actionGoogle_Explore.setText(QCoreApplication.translate("researcher", u"Google Explore", None))
#if QT_CONFIG(shortcut)
        self.actionGoogle_Explore.setShortcut(QCoreApplication.translate("researcher", u"Ctrl+Return", None))
#endif // QT_CONFIG(shortcut)
        self.actionPython_Code_Tester.setText(QCoreApplication.translate("researcher", u"PyTester", None))
#if QT_CONFIG(shortcut)
        self.actionPython_Code_Tester.setShortcut(QCoreApplication.translate("researcher", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionHide_Borders.setText(QCoreApplication.translate("researcher", u"Hide Borders", None))
#if QT_CONFIG(shortcut)
        self.actionHide_Borders.setShortcut(QCoreApplication.translate("researcher", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
        self.action_clearcache.setText(QCoreApplication.translate("researcher", u"Clear Cache and histories", None))
        self.actionRead_chatgpt.setText(QCoreApplication.translate("researcher", u"Read chatgpt", None))
        self.actionClear_History.setText(QCoreApplication.translate("researcher", u"Clear Cache/History", None))
        self.actionShare.setText(QCoreApplication.translate("researcher", u"Share to Community(Telegram)", None))
#if QT_CONFIG(shortcut)
        self.actionShare.setShortcut(QCoreApplication.translate("researcher", u"Ctrl+U", None))
#endif // QT_CONFIG(shortcut)
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("researcher", u"Type Something...", None))
#if QT_CONFIG(tooltip)
        self.toolButton.setToolTip(QCoreApplication.translate("researcher", u"<html><head/><body><p><span style=\" color:#43ff69;\">Custom Search</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.toolButton.setText("")
#if QT_CONFIG(tooltip)
        self.toolButton_mic.setToolTip(QCoreApplication.translate("researcher", u"<html><head/><body><p><span style=\" color:#43ff69;\">Click and say something.</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.toolButton_mic.setText(QCoreApplication.translate("researcher", u"...", None))
#if QT_CONFIG(tooltip)
        self.toolButton_2.setToolTip(QCoreApplication.translate("researcher", u"<html><head/><body><p><span style=\" font-size:9pt; color:#43ff69;\">Minimize all instances</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.toolButton_2.setText(QCoreApplication.translate("researcher", u"-", None))
        self.menuFile.setTitle(QCoreApplication.translate("researcher", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("researcher", u"Edit", None))
        self.menuOptions.setTitle(QCoreApplication.translate("researcher", u"Window", None))
        self.menuRestore.setTitle(QCoreApplication.translate("researcher", u"Restore", None))
        self.menuDefaults.setTitle(QCoreApplication.translate("researcher", u"Plugins", None))
        self.menuScreenshot.setTitle(QCoreApplication.translate("researcher", u"Research", None))
        self.menuLinks.setTitle(QCoreApplication.translate("researcher", u"History", None))
        self.menuAbout.setTitle(QCoreApplication.translate("researcher", u"About", None))
    # retranslateUi

